import GetMsg from './msg/GetMsg';
import GetLoginInfo from './system/GetLoginInfo';
import GetFriendList from './user/GetFriendList';
import GetGroupList from './group/GetGroupList';
import GetGroupInfo from './group/GetGroupInfo';
import GetGroupMemberInfo from './group/GetGroupMemberInfo';
import SendGroupMsg from './group/SendGroupMsg';
import SendPrivateMsg from './msg/SendPrivateMsg';
import SendMsg from './msg/SendMsg';
import DeleteMsg from './msg/DeleteMsg';
import GetVersionInfo from './system/GetVersionInfo';
import CanSendRecord from './system/CanSendRecord';
import CanSendImage from './system/CanSendImage';
import GetStatus from './system/GetStatus';
import { GoCQHTTPSendForwardMsg, GoCQHTTPSendGroupForwardMsg, GoCQHTTPSendPrivateForwardMsg } from './go-cqhttp/SendForwardMsg';
import GoCQHTTPGetStrangerInfo from './go-cqhttp/GetStrangerInfo';
import SendLike from './user/SendLike';
import SetGroupAddRequest from './group/SetGroupAddRequest';
import SetGroupLeave from './group/SetGroupLeave';
import SetFriendAddRequest from './user/SetFriendAddRequest';
import SetGroupWholeBan from './group/SetGroupWholeBan';
import SetGroupName from './group/SetGroupName';
import SetGroupBan from './group/SetGroupBan';
import SetGroupKick from './group/SetGroupKick';
import SetGroupAdmin from './group/SetGroupAdmin';
import SetGroupCard from './group/SetGroupCard';
import GetImage from './file/GetImage';
import GetRecord from './file/GetRecord';
import { GoCQHTTPMarkMsgAsRead, MarkAllMsgAsRead, MarkGroupMsgAsRead, MarkPrivateMsgAsRead } from './msg/MarkMsgAsRead';
import GoCQHTTPUploadGroupFile from './go-cqhttp/UploadGroupFile';
import SetQQAvatar from '../action/extends/SetQQAvatar';
import GoCQHTTPDownloadFile from './go-cqhttp/DownloadFile';
import GoCQHTTPGetGroupMsgHistory from './go-cqhttp/GetGroupMsgHistory';
import GetFile from './file/GetFile';
import { GoCQHTTPGetForwardMsgAction } from './go-cqhttp/GetForwardMsg';
import GetFriendMsgHistory from './go-cqhttp/GetFriendMsgHistory';
import { GetCookies } from './user/GetCookies';
import { SetMsgEmojiLike } from '../action/msg/SetMsgEmojiLike';
import { GetRobotUinRange } from './extends/GetRobotUinRange';
import { SetOnlineStatus } from './extends/SetOnlineStatus';
import { GetGroupNotice } from './group/GetGroupNotice';
import { GetGroupEssence } from './group/GetGroupEssence';
import { ForwardFriendSingleMsg, ForwardGroupSingleMsg } from '../action/msg/ForwardSingleMsg';
import { GetFriendWithCategory } from './extends/GetFriendWithCategory';
import { SendGroupNotice } from './go-cqhttp/SendGroupNotice';
import { GetGroupHonorInfo } from './go-cqhttp/GetGroupHonorInfo';
import { GoCQHTTPHandleQuickAction } from './go-cqhttp/QuickAction';
import { GetGroupIgnoredNotifies } from './group/GetGroupIgnoredNotifies';
import { GetOnlineClient } from './go-cqhttp/GetOnlineClient';
import { IOCRImage, OCRImage } from './extends/OCRImage';
import { TranslateEnWordToZn } from './extends/TranslateEnWordToZn';
import { SetQQProfile } from './go-cqhttp/SetQQProfile';
import { SendArkShare, SendGroupArkShare, ShareGroupEx, SharePeer } from './extends/ShareContact';
import { CreateCollection } from './extends/CreateCollection';
import { SetLongNick } from './extends/SetLongNick';
import DelEssenceMsg from './group/DelEssenceMsg';
import SetEssenceMsg from './group/SetEssenceMsg';
import GetRecentContact from './user/GetRecentContact';
import { GetProfileLike } from './extends/GetProfileLike';
import SetGroupPortrait from './go-cqhttp/SetGroupPortrait';
import { FetchCustomFace } from './extends/FetchCustomFace';
import GoCQHTTPUploadPrivateFile from './go-cqhttp/UploadPrivateFile';
import { FetchEmojiLike } from './extends/FetchEmojiLike';
import { GetEmojiLikes } from './extends/GetEmojiLikes';
import { NapCatCore } from '../../napcat-core';
import type { NetworkAdapterConfig } from '../config/config';
import { OneBotAction } from './OneBotAction';
import { NapCatOneBot11Adapter } from '../../napcat-onebot';
import { SetInputStatus } from './extends/SetInputStatus';
import { GetCSRF } from './system/GetCSRF';
import { DelGroupNotice } from './group/DelGroupNotice';
import { GetGroupInfoEx } from './extends/GetGroupInfoEx';
import { DeleteGroupFile } from '../action/go-cqhttp/DeleteGroupFile';
import { CreateGroupFileFolder } from '../action/go-cqhttp/CreateGroupFileFolder';
import { DeleteGroupFileFolder } from '../action/go-cqhttp/DeleteGroupFileFolder';
import { GetGroupFileSystemInfo } from '../action/go-cqhttp/GetGroupFileSystemInfo';
import { GetGroupRootFiles } from '../action/go-cqhttp/GetGroupRootFiles';
import { GetGroupFilesByFolder } from '../action/go-cqhttp/GetGroupFilesByFolder';
import { GetGroupSystemMsg } from './system/GetSystemMsg';
import { GetUserStatus } from './extends/GetUserStatus';
import { GetRkey } from './extends/GetRkey';
import { SetSpecialTitle } from './extends/SetSpecialTitle';
import { GetGroupShutList } from './group/GetGroupShutList';
import { GetGroupMemberList } from './group/GetGroupMemberList';
import { GetGroupFileUrl } from '../action/file/GetGroupFileUrl';
import { GetPacketStatus } from '../action/packet/GetPacketStatus';
import { GetCredentials } from './system/GetCredentials';
import { SetRestart } from './system/SetRestart';
import { SendGroupSign, SetGroupSign } from './extends/SetGroupSign';
import { GoCQHTTPGetGroupAtAllRemain } from './go-cqhttp/GetGroupAtAllRemain';
import { GoCQHTTPCheckUrlSafely } from './go-cqhttp/GoCQHTTPCheckUrlSafely';
import { GoCQHTTPGetModelShow } from './go-cqhttp/GoCQHTTPGetModelShow';
import { GoCQHTTPSetModelShow } from './go-cqhttp/GoCQHTTPSetModelShow';
import { GoCQHTTPDeleteFriend } from './go-cqhttp/GoCQHTTPDeleteFriend';
import { GetMiniAppArk } from '../action/extends/GetMiniAppArk';
import { GetAiRecord } from '../action/group/GetAiRecord';
import { SendGroupAiRecord } from '../action/group/SendGroupAiRecord';
import { GetAiCharacters } from '../action/extends/GetAiCharacters';
import { GetGuildList } from './guild/GetGuildList';
import { GetGuildProfile } from './guild/GetGuildProfile';
import { GetClientkey } from './extends/GetClientkey';
import { SendPacket } from './extends/SendPacket';
import { FriendPoke, GroupPoke, SendPoke } from '../action/packet/SendPoke';
import { SetDiyOnlineStatus } from './extends/SetDiyOnlineStatus';
import { BotExit } from './extends/BotExit';
import { ClickInlineKeyboardButton } from './extends/ClickInlineKeyboardButton';
import { GetPrivateFileUrl } from './file/GetPrivateFileUrl';
import { GetUnidirectionalFriendList } from './extends/GetUnidirectionalFriendList';
import SetGroupRemark from './extends/SetGroupRemark';
import { MoveGroupFile } from './extends/MoveGroupFile';
import { TransGroupFile } from './extends/TransGroupFile';
import { RenameGroupFile } from './extends/RenameGroupFile';
import { GetRkeyServer } from './packet/GetRkeyServer';
import { GetRkeyEx } from './packet/GetRkeyEx';
import { CleanCache } from './system/CleanCache';
import SetFriendRemark from './user/SetFriendRemark';
import { SetDoubtFriendsAddRequest } from './new/SetDoubtFriendsAddRequest';
import { GetDoubtFriendsAddRequest } from './new/GetDoubtFriendsAddRequest';
import SetGroupAddOption from './extends/SetGroupAddOption';
import SetGroupSearch from './extends/SetGroupSearch';
import SetGroupRobotAddOption from './extends/SetGroupRobotAddOption';
import SetGroupKickMembers from './extends/SetGroupKickMembers';
import { GetGroupDetailInfo } from './group/GetGroupDetailInfo';
import GetGroupAddRequest from './extends/GetGroupAddRequest';
import { GetCollectionList } from './extends/GetCollectionList';
import { SetGroupTodo } from './packet/SetGroupTodo';
import { GetQunAlbumList } from './extends/GetQunAlbumList';
import { UploadImageToQunAlbum } from './extends/UploadImageToQunAlbum';
import { DoGroupAlbumComment } from './extends/DoGroupAlbumComment';
import { GetGroupAlbumMediaList } from './extends/GetGroupAlbumMediaList';
import { SetGroupAlbumMediaLike } from './extends/SetGroupAlbumMediaLike';
import { DelGroupAlbumMedia } from './extends/DelGroupAlbumMedia';
import { CleanStreamTempFile } from './stream/CleanStreamTempFile';
import { DownloadFileStream } from './stream/DownloadFileStream';
import { DownloadFileRecordStream } from './stream/DownloadFileRecordStream';
import { DownloadFileImageStream } from './stream/DownloadFileImageStream';
import { TestDownloadStream } from './stream/TestStreamDownload';
import { UploadFileStream } from './stream/UploadFileStream';
import { CreateFlashTask } from './file/flash/CreateFlashTask';
import { SendFlashMsg } from './file/flash/SendFlashMsg';
import { GetFlashFileList } from './file/flash/GetFlashFileList';
import { GetFlashFileUrl } from './file/flash/GetFlashFileUrl';
import { GetShareLink } from './file/flash/GetShareLink';
import { GetFilesetInfo } from './file/flash/GetFilesetInfo';
import { DownloadFileset } from './file/flash/DownloadFileset';
import { GetOnlineFileMessages } from './file/online/GetOnlineFileMessages';
import { SendOnlineFile } from './file/online/SendOnlineFile';
import { SendOnlineFolder } from './file/online/SendOnlineFolder';
import { CancelOnlineFile } from './file/online/CancelOnlineFile';
import { ReceiveOnlineFile } from './file/online/ReceiveOnlineFile';
import { RefuseOnlineFile } from './file/online/RefuseOnlineFile';
import { GetFilesetId } from './file/flash/GetFilesetIdByCode';
export declare function getAllHandlers(obContext: NapCatOneBot11Adapter, core: NapCatCore): (GetMsg | GetLoginInfo | GetFriendList | GetGroupList | GetGroupInfo | GetGroupMemberInfo | SendMsg | SendGroupMsg | SendPrivateMsg | DeleteMsg | GetVersionInfo | CanSendRecord | CanSendImage | GetStatus | GoCQHTTPSendForwardMsg | GoCQHTTPSendPrivateForwardMsg | GoCQHTTPSendGroupForwardMsg | GoCQHTTPGetStrangerInfo | SendLike | SetGroupAddRequest | SetGroupLeave | SetFriendAddRequest | SetGroupWholeBan | SetGroupName | SetGroupBan | SetGroupKick | SetGroupAdmin | SetGroupCard | GetFile | GetImage | GetRecord | MarkPrivateMsgAsRead | MarkGroupMsgAsRead | GoCQHTTPMarkMsgAsRead | MarkAllMsgAsRead | GoCQHTTPUploadGroupFile | SetQQAvatar | GoCQHTTPDownloadFile | GoCQHTTPGetGroupMsgHistory | GoCQHTTPGetForwardMsgAction | GetFriendMsgHistory | GetCookies | SetMsgEmojiLike | GetRobotUinRange | SetOnlineStatus | GetGroupNotice | GetGroupEssence | ForwardFriendSingleMsg | ForwardGroupSingleMsg | GetFriendWithCategory | SendGroupNotice | GetGroupHonorInfo | GoCQHTTPHandleQuickAction | GetGroupIgnoredNotifies | GetOnlineClient | OCRImage | IOCRImage | TranslateEnWordToZn | SetQQProfile | SharePeer | ShareGroupEx | SendGroupArkShare | SendArkShare | CreateCollection | SetLongNick | DelEssenceMsg | SetEssenceMsg | GetRecentContact | GetProfileLike | SetGroupPortrait | FetchCustomFace | GoCQHTTPUploadPrivateFile | FetchEmojiLike | GetEmojiLikes | SetInputStatus | GetCSRF | DelGroupNotice | GetGroupInfoEx | DeleteGroupFile | CreateGroupFileFolder | DeleteGroupFileFolder | GetGroupFileSystemInfo | GetGroupRootFiles | GetGroupFilesByFolder | GetGroupSystemMsg | GetPacketStatus | GetUserStatus | GetRkey | SetSpecialTitle | GetGroupShutList | GetGroupMemberList | GetGroupFileUrl | GetCredentials | SetRestart | SetGroupSign | SendGroupSign | GoCQHTTPGetGroupAtAllRemain | GoCQHTTPCheckUrlSafely | GoCQHTTPGetModelShow | GoCQHTTPSetModelShow | GoCQHTTPDeleteFriend | GetMiniAppArk | GetAiRecord | SendGroupAiRecord | GetAiCharacters | GetGuildList | GetGuildProfile | GetClientkey | SendPacket | SendPoke | GroupPoke | FriendPoke | SetDiyOnlineStatus | BotExit | ClickInlineKeyboardButton | GetPrivateFileUrl | GetUnidirectionalFriendList | SetGroupRemark | MoveGroupFile | TransGroupFile | RenameGroupFile | GetRkeyServer | GetRkeyEx | CleanCache | SetFriendRemark | SetDoubtFriendsAddRequest | GetDoubtFriendsAddRequest | SetGroupAddOption | SetGroupSearch | SetGroupRobotAddOption | SetGroupKickMembers | GetGroupDetailInfo | GetGroupAddRequest | GetCollectionList | SetGroupTodo | GetQunAlbumList | UploadImageToQunAlbum | DoGroupAlbumComment | GetGroupAlbumMediaList | SetGroupAlbumMediaLike | DelGroupAlbumMedia | CleanStreamTempFile | DownloadFileStream | DownloadFileRecordStream | DownloadFileImageStream | TestDownloadStream | UploadFileStream | CreateFlashTask | SendFlashMsg | GetFlashFileList | GetFlashFileUrl | GetShareLink | GetFilesetInfo | DownloadFileset | GetOnlineFileMessages | SendOnlineFile | SendOnlineFolder | CancelOnlineFile | ReceiveOnlineFile | RefuseOnlineFile | GetFilesetId)[];
export declare function createActionMap(obContext: NapCatOneBot11Adapter, core: NapCatCore): {
    get: <K extends "clean_stream_temp_file" | "test_download_stream" | "upload_file_stream" | "download_file_stream" | "download_file_record_stream" | "download_file_image_stream" | "del_group_album_media" | "set_group_album_media_like" | "do_group_album_comment" | "get_group_album_media_list" | "upload_image_to_qun_album" | "get_qun_album_list" | "set_group_todo" | "set_group_kick_members" | "set_group_robot_add_option" | "set_group_add_option" | "set_group_search" | "get_doubt_friends_add_request" | "set_doubt_friends_add_request" | "get_rkey" | "get_rkey_server" | "set_group_remark" | "get_private_file_url" | "click_inline_keyboard_button" | "get_unidirectional_friend_list" | "send_private_msg" | "send_group_msg" | "send_msg" | "delete_msg" | "get_msg" | "get_forward_msg" | "send_like" | "set_group_kick" | "set_group_ban" | "set_group_whole_ban" | "set_group_admin" | "set_group_card" | "set_group_name" | "set_group_leave" | "set_group_special_title" | "set_friend_add_request" | "set_friend_remark" | "set_group_add_request" | "get_login_info" | "get_stranger_info" | "get_friend_list" | "get_group_info" | "get_group_list" | "get_group_member_info" | "get_group_member_list" | "get_group_honor_info" | "get_cookies" | "get_csrf_token" | "get_credentials" | "get_record" | "get_image" | "can_send_image" | "can_send_record" | "get_status" | "get_version_info" | "set_restart" | "clean_cache" | "bot_exit" | "set_qq_profile" | "_get_model_show" | "_set_model_show" | "get_online_clients" | "delete_friend" | "mark_msg_as_read" | "send_group_forward_msg" | "send_private_forward_msg" | "get_group_msg_history" | "ocr_image" | ".ocr_image" | "get_group_system_msg" | "get_essence_msg_list" | "get_group_at_all_remain" | "set_group_portrait" | "set_essence_msg" | "delete_essence_msg" | "_send_group_notice" | "_get_group_notice" | "upload_group_file" | "delete_group_file" | "create_group_file_folder" | "delete_group_folder" | "get_group_file_system_info" | "get_group_root_files" | "get_group_files_by_folder" | "get_group_file_url" | "upload_private_file" | "download_file" | "check_url_safely" | ".handle_quick_operation" | "set_diy_online_status" | "ArkSharePeer" | "ArkShareGroup" | "send_group_ark_share" | "send_ark_share" | "get_robot_uin_range" | "set_online_status" | "get_friends_with_category" | "set_qq_avatar" | "get_file" | "forward_friend_single_msg" | "forward_group_single_msg" | "translate_en2zh" | "set_msg_emoji_like" | "send_forward_msg" | "mark_private_msg_as_read" | "mark_group_msg_as_read" | "get_friend_msg_history" | "create_collection" | "get_collection_list" | "set_self_longnick" | "get_recent_contact" | "_mark_all_as_read" | "get_profile_like" | "fetch_custom_face" | "fetch_emoji_like" | "get_emoji_likes" | "set_input_status" | "get_group_info_ex" | "get_group_detail_info" | "get_group_ignore_add_request" | "_del_group_notice" | "friend_poke" | "group_poke" | "nc_get_packet_status" | "nc_get_user_status" | "nc_get_rkey" | "get_group_shut_list" | "move_group_file" | "trans_group_file" | "rename_group_file" | "get_guild_list" | "get_guild_service_profile" | "get_group_ignored_notifies" | "set_group_sign" | "send_group_sign" | "send_packet" | "get_mini_app_ark" | "get_ai_record" | "get_ai_characters" | "send_group_ai_record" | "get_clientkey" | "send_poke" | "create_flash_task" | "send_flash_msg" | "get_share_link" | "download_fileset" | "get_fileset_info" | "get_flash_file_list" | "get_flash_file_url" | "get_fileset_id" | "send_online_file" | "send_online_folder" | "get_online_file_msg" | "receive_online_file" | "refuse_online_file" | "cancel_online_file" | "clean_stream_temp_file_async" | "test_download_stream_async" | "upload_file_stream_async" | "download_file_stream_async" | "download_file_record_stream_async" | "download_file_image_stream_async" | "del_group_album_media_async" | "set_group_album_media_like_async" | "do_group_album_comment_async" | "get_group_album_media_list_async" | "upload_image_to_qun_album_async" | "get_qun_album_list_async" | "set_group_todo_async" | "set_group_kick_members_async" | "set_group_robot_add_option_async" | "set_group_add_option_async" | "set_group_search_async" | "get_doubt_friends_add_request_async" | "set_doubt_friends_add_request_async" | "get_rkey_async" | "get_rkey_server_async" | "set_group_remark_async" | "get_private_file_url_async" | "click_inline_keyboard_button_async" | "get_unidirectional_friend_list_async" | "send_private_msg_async" | "send_group_msg_async" | "send_msg_async" | "delete_msg_async" | "get_msg_async" | "get_forward_msg_async" | "send_like_async" | "set_group_kick_async" | "set_group_ban_async" | "set_group_whole_ban_async" | "set_group_admin_async" | "set_group_card_async" | "set_group_name_async" | "set_group_leave_async" | "set_group_special_title_async" | "set_friend_add_request_async" | "set_friend_remark_async" | "set_group_add_request_async" | "get_login_info_async" | "get_stranger_info_async" | "get_friend_list_async" | "get_group_info_async" | "get_group_list_async" | "get_group_member_info_async" | "get_group_member_list_async" | "get_group_honor_info_async" | "get_cookies_async" | "get_csrf_token_async" | "get_credentials_async" | "get_record_async" | "get_image_async" | "can_send_image_async" | "can_send_record_async" | "get_status_async" | "get_version_info_async" | "set_restart_async" | "clean_cache_async" | "bot_exit_async" | "set_qq_profile_async" | "_get_model_show_async" | "_set_model_show_async" | "get_online_clients_async" | "delete_friend_async" | "mark_msg_as_read_async" | "send_group_forward_msg_async" | "send_private_forward_msg_async" | "get_group_msg_history_async" | "ocr_image_async" | ".ocr_image_async" | "get_group_system_msg_async" | "get_essence_msg_list_async" | "get_group_at_all_remain_async" | "set_group_portrait_async" | "set_essence_msg_async" | "delete_essence_msg_async" | "_send_group_notice_async" | "_get_group_notice_async" | "upload_group_file_async" | "delete_group_file_async" | "create_group_file_folder_async" | "delete_group_folder_async" | "get_group_file_system_info_async" | "get_group_root_files_async" | "get_group_files_by_folder_async" | "get_group_file_url_async" | "upload_private_file_async" | "download_file_async" | "check_url_safely_async" | ".handle_quick_operation_async" | "set_diy_online_status_async" | "ArkSharePeer_async" | "ArkShareGroup_async" | "send_group_ark_share_async" | "send_ark_share_async" | "get_robot_uin_range_async" | "set_online_status_async" | "get_friends_with_category_async" | "set_qq_avatar_async" | "get_file_async" | "forward_friend_single_msg_async" | "forward_group_single_msg_async" | "translate_en2zh_async" | "set_msg_emoji_like_async" | "send_forward_msg_async" | "mark_private_msg_as_read_async" | "mark_group_msg_as_read_async" | "get_friend_msg_history_async" | "create_collection_async" | "get_collection_list_async" | "set_self_longnick_async" | "get_recent_contact_async" | "_mark_all_as_read_async" | "get_profile_like_async" | "fetch_custom_face_async" | "fetch_emoji_like_async" | "get_emoji_likes_async" | "set_input_status_async" | "get_group_info_ex_async" | "get_group_detail_info_async" | "get_group_ignore_add_request_async" | "_del_group_notice_async" | "friend_poke_async" | "group_poke_async" | "nc_get_packet_status_async" | "nc_get_user_status_async" | "nc_get_rkey_async" | "get_group_shut_list_async" | "move_group_file_async" | "trans_group_file_async" | "rename_group_file_async" | "get_guild_list_async" | "get_guild_service_profile_async" | "get_group_ignored_notifies_async" | "set_group_sign_async" | "send_group_sign_async" | "send_packet_async" | "get_mini_app_ark_async" | "get_ai_record_async" | "get_ai_characters_async" | "send_group_ai_record_async" | "get_clientkey_async" | "send_poke_async" | "create_flash_task_async" | "send_flash_msg_async" | "get_share_link_async" | "download_fileset_async" | "get_fileset_info_async" | "get_flash_file_list_async" | "get_flash_file_url_async" | "get_fileset_id_async" | "send_online_file_async" | "send_online_folder_async" | "get_online_file_msg_async" | "receive_online_file_async" | "refuse_online_file_async" | "cancel_online_file_async" | "clean_stream_temp_file_rate_limited" | "test_download_stream_rate_limited" | "upload_file_stream_rate_limited" | "download_file_stream_rate_limited" | "download_file_record_stream_rate_limited" | "download_file_image_stream_rate_limited" | "del_group_album_media_rate_limited" | "set_group_album_media_like_rate_limited" | "do_group_album_comment_rate_limited" | "get_group_album_media_list_rate_limited" | "upload_image_to_qun_album_rate_limited" | "get_qun_album_list_rate_limited" | "set_group_todo_rate_limited" | "set_group_kick_members_rate_limited" | "set_group_robot_add_option_rate_limited" | "set_group_add_option_rate_limited" | "set_group_search_rate_limited" | "get_doubt_friends_add_request_rate_limited" | "set_doubt_friends_add_request_rate_limited" | "get_rkey_rate_limited" | "get_rkey_server_rate_limited" | "set_group_remark_rate_limited" | "get_private_file_url_rate_limited" | "click_inline_keyboard_button_rate_limited" | "get_unidirectional_friend_list_rate_limited" | "send_private_msg_rate_limited" | "send_group_msg_rate_limited" | "send_msg_rate_limited" | "delete_msg_rate_limited" | "get_msg_rate_limited" | "get_forward_msg_rate_limited" | "send_like_rate_limited" | "set_group_kick_rate_limited" | "set_group_ban_rate_limited" | "set_group_whole_ban_rate_limited" | "set_group_admin_rate_limited" | "set_group_card_rate_limited" | "set_group_name_rate_limited" | "set_group_leave_rate_limited" | "set_group_special_title_rate_limited" | "set_friend_add_request_rate_limited" | "set_friend_remark_rate_limited" | "set_group_add_request_rate_limited" | "get_login_info_rate_limited" | "get_stranger_info_rate_limited" | "get_friend_list_rate_limited" | "get_group_info_rate_limited" | "get_group_list_rate_limited" | "get_group_member_info_rate_limited" | "get_group_member_list_rate_limited" | "get_group_honor_info_rate_limited" | "get_cookies_rate_limited" | "get_csrf_token_rate_limited" | "get_credentials_rate_limited" | "get_record_rate_limited" | "get_image_rate_limited" | "can_send_image_rate_limited" | "can_send_record_rate_limited" | "get_status_rate_limited" | "get_version_info_rate_limited" | "set_restart_rate_limited" | "clean_cache_rate_limited" | "bot_exit_rate_limited" | "set_qq_profile_rate_limited" | "_get_model_show_rate_limited" | "_set_model_show_rate_limited" | "get_online_clients_rate_limited" | "delete_friend_rate_limited" | "mark_msg_as_read_rate_limited" | "send_group_forward_msg_rate_limited" | "send_private_forward_msg_rate_limited" | "get_group_msg_history_rate_limited" | "ocr_image_rate_limited" | ".ocr_image_rate_limited" | "get_group_system_msg_rate_limited" | "get_essence_msg_list_rate_limited" | "get_group_at_all_remain_rate_limited" | "set_group_portrait_rate_limited" | "set_essence_msg_rate_limited" | "delete_essence_msg_rate_limited" | "_send_group_notice_rate_limited" | "_get_group_notice_rate_limited" | "upload_group_file_rate_limited" | "delete_group_file_rate_limited" | "create_group_file_folder_rate_limited" | "delete_group_folder_rate_limited" | "get_group_file_system_info_rate_limited" | "get_group_root_files_rate_limited" | "get_group_files_by_folder_rate_limited" | "get_group_file_url_rate_limited" | "upload_private_file_rate_limited" | "download_file_rate_limited" | "check_url_safely_rate_limited" | ".handle_quick_operation_rate_limited" | "set_diy_online_status_rate_limited" | "ArkSharePeer_rate_limited" | "ArkShareGroup_rate_limited" | "send_group_ark_share_rate_limited" | "send_ark_share_rate_limited" | "get_robot_uin_range_rate_limited" | "set_online_status_rate_limited" | "get_friends_with_category_rate_limited" | "set_qq_avatar_rate_limited" | "get_file_rate_limited" | "forward_friend_single_msg_rate_limited" | "forward_group_single_msg_rate_limited" | "translate_en2zh_rate_limited" | "set_msg_emoji_like_rate_limited" | "send_forward_msg_rate_limited" | "mark_private_msg_as_read_rate_limited" | "mark_group_msg_as_read_rate_limited" | "get_friend_msg_history_rate_limited" | "create_collection_rate_limited" | "get_collection_list_rate_limited" | "set_self_longnick_rate_limited" | "get_recent_contact_rate_limited" | "_mark_all_as_read_rate_limited" | "get_profile_like_rate_limited" | "fetch_custom_face_rate_limited" | "fetch_emoji_like_rate_limited" | "get_emoji_likes_rate_limited" | "set_input_status_rate_limited" | "get_group_info_ex_rate_limited" | "get_group_detail_info_rate_limited" | "get_group_ignore_add_request_rate_limited" | "_del_group_notice_rate_limited" | "friend_poke_rate_limited" | "group_poke_rate_limited" | "nc_get_packet_status_rate_limited" | "nc_get_user_status_rate_limited" | "nc_get_rkey_rate_limited" | "get_group_shut_list_rate_limited" | "move_group_file_rate_limited" | "trans_group_file_rate_limited" | "rename_group_file_rate_limited" | "get_guild_list_rate_limited" | "get_guild_service_profile_rate_limited" | "get_group_ignored_notifies_rate_limited" | "set_group_sign_rate_limited" | "send_group_sign_rate_limited" | "send_packet_rate_limited" | "get_mini_app_ark_rate_limited" | "get_ai_record_rate_limited" | "get_ai_characters_rate_limited" | "send_group_ai_record_rate_limited" | "get_clientkey_rate_limited" | "send_poke_rate_limited" | "create_flash_task_rate_limited" | "send_flash_msg_rate_limited" | "get_share_link_rate_limited" | "download_fileset_rate_limited" | "get_fileset_info_rate_limited" | "get_flash_file_list_rate_limited" | "get_flash_file_url_rate_limited" | "get_fileset_id_rate_limited" | "send_online_file_rate_limited" | "send_online_folder_rate_limited" | "get_online_file_msg_rate_limited" | "receive_online_file_rate_limited" | "refuse_online_file_rate_limited" | "cancel_online_file_rate_limited">(key: K) => ({
        get_msg: GetMsg;
        get_login_info: GetLoginInfo;
        get_friend_list: GetFriendList;
        get_group_list: GetGroupList;
        get_group_info: GetGroupInfo;
        get_group_member_info: GetGroupMemberInfo;
        send_msg: SendMsg;
        send_group_msg: SendGroupMsg;
        send_private_msg: SendPrivateMsg;
        delete_msg: DeleteMsg;
        get_version_info: GetVersionInfo;
        can_send_record: CanSendRecord;
        can_send_image: CanSendImage;
        get_status: GetStatus;
        send_forward_msg: GoCQHTTPSendForwardMsg;
        send_private_forward_msg: GoCQHTTPSendPrivateForwardMsg;
        send_group_forward_msg: GoCQHTTPSendGroupForwardMsg;
        get_stranger_info: GoCQHTTPGetStrangerInfo;
        send_like: SendLike;
        set_group_add_request: SetGroupAddRequest;
        set_group_leave: SetGroupLeave;
        set_friend_add_request: SetFriendAddRequest;
        set_group_whole_ban: SetGroupWholeBan;
        set_group_name: SetGroupName;
        set_group_ban: SetGroupBan;
        set_group_kick: SetGroupKick;
        set_group_admin: SetGroupAdmin;
        set_group_card: SetGroupCard;
        get_file: GetFile;
        get_image: GetImage;
        get_record: GetRecord;
        mark_private_msg_as_read: MarkPrivateMsgAsRead;
        mark_group_msg_as_read: MarkGroupMsgAsRead;
        mark_msg_as_read: GoCQHTTPMarkMsgAsRead;
        _mark_all_as_read: MarkAllMsgAsRead;
        upload_group_file: GoCQHTTPUploadGroupFile;
        set_qq_avatar: SetQQAvatar;
        download_file: GoCQHTTPDownloadFile;
        get_group_msg_history: GoCQHTTPGetGroupMsgHistory;
        get_forward_msg: GoCQHTTPGetForwardMsgAction;
        get_friend_msg_history: GetFriendMsgHistory;
        get_cookies: GetCookies;
        set_msg_emoji_like: SetMsgEmojiLike;
        get_robot_uin_range: GetRobotUinRange;
        set_online_status: SetOnlineStatus;
        _get_group_notice: GetGroupNotice;
        get_essence_msg_list: GetGroupEssence;
        forward_friend_single_msg: ForwardFriendSingleMsg;
        forward_group_single_msg: ForwardGroupSingleMsg;
        get_friends_with_category: GetFriendWithCategory;
        _send_group_notice: SendGroupNotice;
        get_group_honor_info: GetGroupHonorInfo;
        ".handle_quick_operation": GoCQHTTPHandleQuickAction;
        get_group_ignored_notifies: GetGroupIgnoredNotifies;
        get_online_clients: GetOnlineClient;
        ocr_image: OCRImage;
        ".ocr_image": IOCRImage;
        translate_en2zh: TranslateEnWordToZn;
        set_qq_profile: SetQQProfile;
        ArkSharePeer: SharePeer;
        ArkShareGroup: ShareGroupEx;
        send_group_ark_share: SendGroupArkShare;
        send_ark_share: SendArkShare;
        create_collection: CreateCollection;
        set_self_longnick: SetLongNick;
        delete_essence_msg: DelEssenceMsg;
        set_essence_msg: SetEssenceMsg;
        get_recent_contact: GetRecentContact;
        get_profile_like: GetProfileLike;
        set_group_portrait: SetGroupPortrait;
        fetch_custom_face: FetchCustomFace;
        upload_private_file: GoCQHTTPUploadPrivateFile;
        fetch_emoji_like: FetchEmojiLike;
        get_emoji_likes: GetEmojiLikes;
        set_input_status: SetInputStatus;
        get_csrf_token: GetCSRF;
        _del_group_notice: DelGroupNotice;
        get_group_info_ex: GetGroupInfoEx;
        delete_group_file: DeleteGroupFile;
        create_group_file_folder: CreateGroupFileFolder;
        delete_group_folder: DeleteGroupFileFolder;
        get_group_file_system_info: GetGroupFileSystemInfo;
        get_group_root_files: GetGroupRootFiles;
        get_group_files_by_folder: GetGroupFilesByFolder;
        get_group_system_msg: GetGroupSystemMsg;
        nc_get_packet_status: GetPacketStatus;
        nc_get_user_status: GetUserStatus;
        nc_get_rkey: GetRkey;
        set_group_special_title: SetSpecialTitle;
        get_group_shut_list: GetGroupShutList;
        get_group_member_list: GetGroupMemberList;
        get_group_file_url: GetGroupFileUrl;
        get_credentials: GetCredentials;
        set_restart: SetRestart;
        set_group_sign: SetGroupSign;
        send_group_sign: SendGroupSign;
        get_group_at_all_remain: GoCQHTTPGetGroupAtAllRemain;
        check_url_safely: GoCQHTTPCheckUrlSafely;
        _get_model_show: GoCQHTTPGetModelShow;
        _set_model_show: GoCQHTTPSetModelShow;
        delete_friend: GoCQHTTPDeleteFriend;
        get_mini_app_ark: GetMiniAppArk;
        get_ai_record: GetAiRecord;
        send_group_ai_record: SendGroupAiRecord;
        get_ai_characters: GetAiCharacters;
        get_guild_list: GetGuildList;
        get_guild_service_profile: GetGuildProfile;
        get_clientkey: GetClientkey;
        send_packet: SendPacket;
        send_poke: SendPoke;
        group_poke: GroupPoke;
        friend_poke: FriendPoke;
        set_diy_online_status: SetDiyOnlineStatus;
        bot_exit: BotExit;
        click_inline_keyboard_button: ClickInlineKeyboardButton;
        get_private_file_url: GetPrivateFileUrl;
        get_unidirectional_friend_list: GetUnidirectionalFriendList;
        set_group_remark: SetGroupRemark;
        move_group_file: MoveGroupFile;
        trans_group_file: TransGroupFile;
        rename_group_file: RenameGroupFile;
        get_rkey_server: GetRkeyServer;
        get_rkey: GetRkeyEx;
        clean_cache: CleanCache;
        set_friend_remark: SetFriendRemark;
        set_doubt_friends_add_request: SetDoubtFriendsAddRequest;
        get_doubt_friends_add_request: GetDoubtFriendsAddRequest;
        set_group_add_option: SetGroupAddOption;
        set_group_search: SetGroupSearch;
        set_group_robot_add_option: SetGroupRobotAddOption;
        set_group_kick_members: SetGroupKickMembers;
        get_group_detail_info: GetGroupDetailInfo;
        get_group_ignore_add_request: GetGroupAddRequest;
        get_collection_list: GetCollectionList;
        set_group_todo: SetGroupTodo;
        get_qun_album_list: GetQunAlbumList;
        upload_image_to_qun_album: UploadImageToQunAlbum;
        do_group_album_comment: DoGroupAlbumComment;
        get_group_album_media_list: GetGroupAlbumMediaList;
        set_group_album_media_like: SetGroupAlbumMediaLike;
        del_group_album_media: DelGroupAlbumMedia;
        clean_stream_temp_file: CleanStreamTempFile;
        download_file_stream: DownloadFileStream;
        download_file_record_stream: DownloadFileRecordStream;
        download_file_image_stream: DownloadFileImageStream;
        test_download_stream: TestDownloadStream;
        upload_file_stream: UploadFileStream;
        create_flash_task: CreateFlashTask;
        send_flash_msg: SendFlashMsg;
        get_flash_file_list: GetFlashFileList;
        get_flash_file_url: GetFlashFileUrl;
        get_share_link: GetShareLink;
        get_fileset_info: GetFilesetInfo;
        download_fileset: DownloadFileset;
        get_online_file_msg: GetOnlineFileMessages;
        send_online_file: SendOnlineFile;
        send_online_folder: SendOnlineFolder;
        cancel_online_file: CancelOnlineFile;
        receive_online_file: ReceiveOnlineFile;
        refuse_online_file: RefuseOnlineFile;
        get_fileset_id: GetFilesetId;
    } & {
        get_msg_async: GetMsg;
        get_login_info_async: GetLoginInfo;
        get_friend_list_async: GetFriendList;
        get_group_list_async: GetGroupList;
        get_group_info_async: GetGroupInfo;
        get_group_member_info_async: GetGroupMemberInfo;
        send_msg_async: SendMsg;
        send_group_msg_async: SendGroupMsg;
        send_private_msg_async: SendPrivateMsg;
        delete_msg_async: DeleteMsg;
        get_version_info_async: GetVersionInfo;
        can_send_record_async: CanSendRecord;
        can_send_image_async: CanSendImage;
        get_status_async: GetStatus;
        send_forward_msg_async: GoCQHTTPSendForwardMsg;
        send_private_forward_msg_async: GoCQHTTPSendPrivateForwardMsg;
        send_group_forward_msg_async: GoCQHTTPSendGroupForwardMsg;
        get_stranger_info_async: GoCQHTTPGetStrangerInfo;
        send_like_async: SendLike;
        set_group_add_request_async: SetGroupAddRequest;
        set_group_leave_async: SetGroupLeave;
        set_friend_add_request_async: SetFriendAddRequest;
        set_group_whole_ban_async: SetGroupWholeBan;
        set_group_name_async: SetGroupName;
        set_group_ban_async: SetGroupBan;
        set_group_kick_async: SetGroupKick;
        set_group_admin_async: SetGroupAdmin;
        set_group_card_async: SetGroupCard;
        get_file_async: GetFile;
        get_image_async: GetImage;
        get_record_async: GetRecord;
        mark_private_msg_as_read_async: MarkPrivateMsgAsRead;
        mark_group_msg_as_read_async: MarkGroupMsgAsRead;
        mark_msg_as_read_async: GoCQHTTPMarkMsgAsRead;
        _mark_all_as_read_async: MarkAllMsgAsRead;
        upload_group_file_async: GoCQHTTPUploadGroupFile;
        set_qq_avatar_async: SetQQAvatar;
        download_file_async: GoCQHTTPDownloadFile;
        get_group_msg_history_async: GoCQHTTPGetGroupMsgHistory;
        get_forward_msg_async: GoCQHTTPGetForwardMsgAction;
        get_friend_msg_history_async: GetFriendMsgHistory;
        get_cookies_async: GetCookies;
        set_msg_emoji_like_async: SetMsgEmojiLike;
        get_robot_uin_range_async: GetRobotUinRange;
        set_online_status_async: SetOnlineStatus;
        _get_group_notice_async: GetGroupNotice;
        get_essence_msg_list_async: GetGroupEssence;
        forward_friend_single_msg_async: ForwardFriendSingleMsg;
        forward_group_single_msg_async: ForwardGroupSingleMsg;
        get_friends_with_category_async: GetFriendWithCategory;
        _send_group_notice_async: SendGroupNotice;
        get_group_honor_info_async: GetGroupHonorInfo;
        ".handle_quick_operation_async": GoCQHTTPHandleQuickAction;
        get_group_ignored_notifies_async: GetGroupIgnoredNotifies;
        get_online_clients_async: GetOnlineClient;
        ocr_image_async: OCRImage;
        ".ocr_image_async": IOCRImage;
        translate_en2zh_async: TranslateEnWordToZn;
        set_qq_profile_async: SetQQProfile;
        ArkSharePeer_async: SharePeer;
        ArkShareGroup_async: ShareGroupEx;
        send_group_ark_share_async: SendGroupArkShare;
        send_ark_share_async: SendArkShare;
        create_collection_async: CreateCollection;
        set_self_longnick_async: SetLongNick;
        delete_essence_msg_async: DelEssenceMsg;
        set_essence_msg_async: SetEssenceMsg;
        get_recent_contact_async: GetRecentContact;
        get_profile_like_async: GetProfileLike;
        set_group_portrait_async: SetGroupPortrait;
        fetch_custom_face_async: FetchCustomFace;
        upload_private_file_async: GoCQHTTPUploadPrivateFile;
        fetch_emoji_like_async: FetchEmojiLike;
        get_emoji_likes_async: GetEmojiLikes;
        set_input_status_async: SetInputStatus;
        get_csrf_token_async: GetCSRF;
        _del_group_notice_async: DelGroupNotice;
        get_group_info_ex_async: GetGroupInfoEx;
        delete_group_file_async: DeleteGroupFile;
        create_group_file_folder_async: CreateGroupFileFolder;
        delete_group_folder_async: DeleteGroupFileFolder;
        get_group_file_system_info_async: GetGroupFileSystemInfo;
        get_group_root_files_async: GetGroupRootFiles;
        get_group_files_by_folder_async: GetGroupFilesByFolder;
        get_group_system_msg_async: GetGroupSystemMsg;
        nc_get_packet_status_async: GetPacketStatus;
        nc_get_user_status_async: GetUserStatus;
        nc_get_rkey_async: GetRkey;
        set_group_special_title_async: SetSpecialTitle;
        get_group_shut_list_async: GetGroupShutList;
        get_group_member_list_async: GetGroupMemberList;
        get_group_file_url_async: GetGroupFileUrl;
        get_credentials_async: GetCredentials;
        set_restart_async: SetRestart;
        set_group_sign_async: SetGroupSign;
        send_group_sign_async: SendGroupSign;
        get_group_at_all_remain_async: GoCQHTTPGetGroupAtAllRemain;
        check_url_safely_async: GoCQHTTPCheckUrlSafely;
        _get_model_show_async: GoCQHTTPGetModelShow;
        _set_model_show_async: GoCQHTTPSetModelShow;
        delete_friend_async: GoCQHTTPDeleteFriend;
        get_mini_app_ark_async: GetMiniAppArk;
        get_ai_record_async: GetAiRecord;
        send_group_ai_record_async: SendGroupAiRecord;
        get_ai_characters_async: GetAiCharacters;
        get_guild_list_async: GetGuildList;
        get_guild_service_profile_async: GetGuildProfile;
        get_clientkey_async: GetClientkey;
        send_packet_async: SendPacket;
        send_poke_async: SendPoke;
        group_poke_async: GroupPoke;
        friend_poke_async: FriendPoke;
        set_diy_online_status_async: SetDiyOnlineStatus;
        bot_exit_async: BotExit;
        click_inline_keyboard_button_async: ClickInlineKeyboardButton;
        get_private_file_url_async: GetPrivateFileUrl;
        get_unidirectional_friend_list_async: GetUnidirectionalFriendList;
        set_group_remark_async: SetGroupRemark;
        move_group_file_async: MoveGroupFile;
        trans_group_file_async: TransGroupFile;
        rename_group_file_async: RenameGroupFile;
        get_rkey_server_async: GetRkeyServer;
        get_rkey_async: GetRkeyEx;
        clean_cache_async: CleanCache;
        set_friend_remark_async: SetFriendRemark;
        set_doubt_friends_add_request_async: SetDoubtFriendsAddRequest;
        get_doubt_friends_add_request_async: GetDoubtFriendsAddRequest;
        set_group_add_option_async: SetGroupAddOption;
        set_group_search_async: SetGroupSearch;
        set_group_robot_add_option_async: SetGroupRobotAddOption;
        set_group_kick_members_async: SetGroupKickMembers;
        get_group_detail_info_async: GetGroupDetailInfo;
        get_group_ignore_add_request_async: GetGroupAddRequest;
        get_collection_list_async: GetCollectionList;
        set_group_todo_async: SetGroupTodo;
        get_qun_album_list_async: GetQunAlbumList;
        upload_image_to_qun_album_async: UploadImageToQunAlbum;
        do_group_album_comment_async: DoGroupAlbumComment;
        get_group_album_media_list_async: GetGroupAlbumMediaList;
        set_group_album_media_like_async: SetGroupAlbumMediaLike;
        del_group_album_media_async: DelGroupAlbumMedia;
        clean_stream_temp_file_async: CleanStreamTempFile;
        download_file_stream_async: DownloadFileStream;
        download_file_record_stream_async: DownloadFileRecordStream;
        download_file_image_stream_async: DownloadFileImageStream;
        test_download_stream_async: TestDownloadStream;
        upload_file_stream_async: UploadFileStream;
        create_flash_task_async: CreateFlashTask;
        send_flash_msg_async: SendFlashMsg;
        get_flash_file_list_async: GetFlashFileList;
        get_flash_file_url_async: GetFlashFileUrl;
        get_share_link_async: GetShareLink;
        get_fileset_info_async: GetFilesetInfo;
        download_fileset_async: DownloadFileset;
        get_online_file_msg_async: GetOnlineFileMessages;
        send_online_file_async: SendOnlineFile;
        send_online_folder_async: SendOnlineFolder;
        cancel_online_file_async: CancelOnlineFile;
        receive_online_file_async: ReceiveOnlineFile;
        refuse_online_file_async: RefuseOnlineFile;
        get_fileset_id_async: GetFilesetId;
    } & {
        get_msg_rate_limited: GetMsg;
        get_login_info_rate_limited: GetLoginInfo;
        get_friend_list_rate_limited: GetFriendList;
        get_group_list_rate_limited: GetGroupList;
        get_group_info_rate_limited: GetGroupInfo;
        get_group_member_info_rate_limited: GetGroupMemberInfo;
        send_msg_rate_limited: SendMsg;
        send_group_msg_rate_limited: SendGroupMsg;
        send_private_msg_rate_limited: SendPrivateMsg;
        delete_msg_rate_limited: DeleteMsg;
        get_version_info_rate_limited: GetVersionInfo;
        can_send_record_rate_limited: CanSendRecord;
        can_send_image_rate_limited: CanSendImage;
        get_status_rate_limited: GetStatus;
        send_forward_msg_rate_limited: GoCQHTTPSendForwardMsg;
        send_private_forward_msg_rate_limited: GoCQHTTPSendPrivateForwardMsg;
        send_group_forward_msg_rate_limited: GoCQHTTPSendGroupForwardMsg;
        get_stranger_info_rate_limited: GoCQHTTPGetStrangerInfo;
        send_like_rate_limited: SendLike;
        set_group_add_request_rate_limited: SetGroupAddRequest;
        set_group_leave_rate_limited: SetGroupLeave;
        set_friend_add_request_rate_limited: SetFriendAddRequest;
        set_group_whole_ban_rate_limited: SetGroupWholeBan;
        set_group_name_rate_limited: SetGroupName;
        set_group_ban_rate_limited: SetGroupBan;
        set_group_kick_rate_limited: SetGroupKick;
        set_group_admin_rate_limited: SetGroupAdmin;
        set_group_card_rate_limited: SetGroupCard;
        get_file_rate_limited: GetFile;
        get_image_rate_limited: GetImage;
        get_record_rate_limited: GetRecord;
        mark_private_msg_as_read_rate_limited: MarkPrivateMsgAsRead;
        mark_group_msg_as_read_rate_limited: MarkGroupMsgAsRead;
        mark_msg_as_read_rate_limited: GoCQHTTPMarkMsgAsRead;
        _mark_all_as_read_rate_limited: MarkAllMsgAsRead;
        upload_group_file_rate_limited: GoCQHTTPUploadGroupFile;
        set_qq_avatar_rate_limited: SetQQAvatar;
        download_file_rate_limited: GoCQHTTPDownloadFile;
        get_group_msg_history_rate_limited: GoCQHTTPGetGroupMsgHistory;
        get_forward_msg_rate_limited: GoCQHTTPGetForwardMsgAction;
        get_friend_msg_history_rate_limited: GetFriendMsgHistory;
        get_cookies_rate_limited: GetCookies;
        set_msg_emoji_like_rate_limited: SetMsgEmojiLike;
        get_robot_uin_range_rate_limited: GetRobotUinRange;
        set_online_status_rate_limited: SetOnlineStatus;
        _get_group_notice_rate_limited: GetGroupNotice;
        get_essence_msg_list_rate_limited: GetGroupEssence;
        forward_friend_single_msg_rate_limited: ForwardFriendSingleMsg;
        forward_group_single_msg_rate_limited: ForwardGroupSingleMsg;
        get_friends_with_category_rate_limited: GetFriendWithCategory;
        _send_group_notice_rate_limited: SendGroupNotice;
        get_group_honor_info_rate_limited: GetGroupHonorInfo;
        ".handle_quick_operation_rate_limited": GoCQHTTPHandleQuickAction;
        get_group_ignored_notifies_rate_limited: GetGroupIgnoredNotifies;
        get_online_clients_rate_limited: GetOnlineClient;
        ocr_image_rate_limited: OCRImage;
        ".ocr_image_rate_limited": IOCRImage;
        translate_en2zh_rate_limited: TranslateEnWordToZn;
        set_qq_profile_rate_limited: SetQQProfile;
        ArkSharePeer_rate_limited: SharePeer;
        ArkShareGroup_rate_limited: ShareGroupEx;
        send_group_ark_share_rate_limited: SendGroupArkShare;
        send_ark_share_rate_limited: SendArkShare;
        create_collection_rate_limited: CreateCollection;
        set_self_longnick_rate_limited: SetLongNick;
        delete_essence_msg_rate_limited: DelEssenceMsg;
        set_essence_msg_rate_limited: SetEssenceMsg;
        get_recent_contact_rate_limited: GetRecentContact;
        get_profile_like_rate_limited: GetProfileLike;
        set_group_portrait_rate_limited: SetGroupPortrait;
        fetch_custom_face_rate_limited: FetchCustomFace;
        upload_private_file_rate_limited: GoCQHTTPUploadPrivateFile;
        fetch_emoji_like_rate_limited: FetchEmojiLike;
        get_emoji_likes_rate_limited: GetEmojiLikes;
        set_input_status_rate_limited: SetInputStatus;
        get_csrf_token_rate_limited: GetCSRF;
        _del_group_notice_rate_limited: DelGroupNotice;
        get_group_info_ex_rate_limited: GetGroupInfoEx;
        delete_group_file_rate_limited: DeleteGroupFile;
        create_group_file_folder_rate_limited: CreateGroupFileFolder;
        delete_group_folder_rate_limited: DeleteGroupFileFolder;
        get_group_file_system_info_rate_limited: GetGroupFileSystemInfo;
        get_group_root_files_rate_limited: GetGroupRootFiles;
        get_group_files_by_folder_rate_limited: GetGroupFilesByFolder;
        get_group_system_msg_rate_limited: GetGroupSystemMsg;
        nc_get_packet_status_rate_limited: GetPacketStatus;
        nc_get_user_status_rate_limited: GetUserStatus;
        nc_get_rkey_rate_limited: GetRkey;
        set_group_special_title_rate_limited: SetSpecialTitle;
        get_group_shut_list_rate_limited: GetGroupShutList;
        get_group_member_list_rate_limited: GetGroupMemberList;
        get_group_file_url_rate_limited: GetGroupFileUrl;
        get_credentials_rate_limited: GetCredentials;
        set_restart_rate_limited: SetRestart;
        set_group_sign_rate_limited: SetGroupSign;
        send_group_sign_rate_limited: SendGroupSign;
        get_group_at_all_remain_rate_limited: GoCQHTTPGetGroupAtAllRemain;
        check_url_safely_rate_limited: GoCQHTTPCheckUrlSafely;
        _get_model_show_rate_limited: GoCQHTTPGetModelShow;
        _set_model_show_rate_limited: GoCQHTTPSetModelShow;
        delete_friend_rate_limited: GoCQHTTPDeleteFriend;
        get_mini_app_ark_rate_limited: GetMiniAppArk;
        get_ai_record_rate_limited: GetAiRecord;
        send_group_ai_record_rate_limited: SendGroupAiRecord;
        get_ai_characters_rate_limited: GetAiCharacters;
        get_guild_list_rate_limited: GetGuildList;
        get_guild_service_profile_rate_limited: GetGuildProfile;
        get_clientkey_rate_limited: GetClientkey;
        send_packet_rate_limited: SendPacket;
        send_poke_rate_limited: SendPoke;
        group_poke_rate_limited: GroupPoke;
        friend_poke_rate_limited: FriendPoke;
        set_diy_online_status_rate_limited: SetDiyOnlineStatus;
        bot_exit_rate_limited: BotExit;
        click_inline_keyboard_button_rate_limited: ClickInlineKeyboardButton;
        get_private_file_url_rate_limited: GetPrivateFileUrl;
        get_unidirectional_friend_list_rate_limited: GetUnidirectionalFriendList;
        set_group_remark_rate_limited: SetGroupRemark;
        move_group_file_rate_limited: MoveGroupFile;
        trans_group_file_rate_limited: TransGroupFile;
        rename_group_file_rate_limited: RenameGroupFile;
        get_rkey_server_rate_limited: GetRkeyServer;
        get_rkey_rate_limited: GetRkeyEx;
        clean_cache_rate_limited: CleanCache;
        set_friend_remark_rate_limited: SetFriendRemark;
        set_doubt_friends_add_request_rate_limited: SetDoubtFriendsAddRequest;
        get_doubt_friends_add_request_rate_limited: GetDoubtFriendsAddRequest;
        set_group_add_option_rate_limited: SetGroupAddOption;
        set_group_search_rate_limited: SetGroupSearch;
        set_group_robot_add_option_rate_limited: SetGroupRobotAddOption;
        set_group_kick_members_rate_limited: SetGroupKickMembers;
        get_group_detail_info_rate_limited: GetGroupDetailInfo;
        get_group_ignore_add_request_rate_limited: GetGroupAddRequest;
        get_collection_list_rate_limited: GetCollectionList;
        set_group_todo_rate_limited: SetGroupTodo;
        get_qun_album_list_rate_limited: GetQunAlbumList;
        upload_image_to_qun_album_rate_limited: UploadImageToQunAlbum;
        do_group_album_comment_rate_limited: DoGroupAlbumComment;
        get_group_album_media_list_rate_limited: GetGroupAlbumMediaList;
        set_group_album_media_like_rate_limited: SetGroupAlbumMediaLike;
        del_group_album_media_rate_limited: DelGroupAlbumMedia;
        clean_stream_temp_file_rate_limited: CleanStreamTempFile;
        download_file_stream_rate_limited: DownloadFileStream;
        download_file_record_stream_rate_limited: DownloadFileRecordStream;
        download_file_image_stream_rate_limited: DownloadFileImageStream;
        test_download_stream_rate_limited: TestDownloadStream;
        upload_file_stream_rate_limited: UploadFileStream;
        create_flash_task_rate_limited: CreateFlashTask;
        send_flash_msg_rate_limited: SendFlashMsg;
        get_flash_file_list_rate_limited: GetFlashFileList;
        get_flash_file_url_rate_limited: GetFlashFileUrl;
        get_share_link_rate_limited: GetShareLink;
        get_fileset_info_rate_limited: GetFilesetInfo;
        download_fileset_rate_limited: DownloadFileset;
        get_online_file_msg_rate_limited: GetOnlineFileMessages;
        send_online_file_rate_limited: SendOnlineFile;
        send_online_folder_rate_limited: SendOnlineFolder;
        cancel_online_file_rate_limited: CancelOnlineFile;
        receive_online_file_rate_limited: ReceiveOnlineFile;
        refuse_online_file_rate_limited: RefuseOnlineFile;
        get_fileset_id_rate_limited: GetFilesetId;
    })[K] | undefined;
    call: <K extends "clean_stream_temp_file" | "test_download_stream" | "upload_file_stream" | "download_file_stream" | "download_file_record_stream" | "download_file_image_stream" | "del_group_album_media" | "set_group_album_media_like" | "do_group_album_comment" | "get_group_album_media_list" | "upload_image_to_qun_album" | "get_qun_album_list" | "set_group_todo" | "set_group_kick_members" | "set_group_robot_add_option" | "set_group_add_option" | "set_group_search" | "get_doubt_friends_add_request" | "set_doubt_friends_add_request" | "get_rkey" | "get_rkey_server" | "set_group_remark" | "get_private_file_url" | "click_inline_keyboard_button" | "get_unidirectional_friend_list" | "send_private_msg" | "send_group_msg" | "send_msg" | "delete_msg" | "get_msg" | "get_forward_msg" | "send_like" | "set_group_kick" | "set_group_ban" | "set_group_whole_ban" | "set_group_admin" | "set_group_card" | "set_group_name" | "set_group_leave" | "set_group_special_title" | "set_friend_add_request" | "set_friend_remark" | "set_group_add_request" | "get_login_info" | "get_stranger_info" | "get_friend_list" | "get_group_info" | "get_group_list" | "get_group_member_info" | "get_group_member_list" | "get_group_honor_info" | "get_cookies" | "get_csrf_token" | "get_credentials" | "get_record" | "get_image" | "can_send_image" | "can_send_record" | "get_status" | "get_version_info" | "set_restart" | "clean_cache" | "bot_exit" | "set_qq_profile" | "_get_model_show" | "_set_model_show" | "get_online_clients" | "delete_friend" | "mark_msg_as_read" | "send_group_forward_msg" | "send_private_forward_msg" | "get_group_msg_history" | "ocr_image" | ".ocr_image" | "get_group_system_msg" | "get_essence_msg_list" | "get_group_at_all_remain" | "set_group_portrait" | "set_essence_msg" | "delete_essence_msg" | "_send_group_notice" | "_get_group_notice" | "upload_group_file" | "delete_group_file" | "create_group_file_folder" | "delete_group_folder" | "get_group_file_system_info" | "get_group_root_files" | "get_group_files_by_folder" | "get_group_file_url" | "upload_private_file" | "download_file" | "check_url_safely" | ".handle_quick_operation" | "set_diy_online_status" | "ArkSharePeer" | "ArkShareGroup" | "send_group_ark_share" | "send_ark_share" | "get_robot_uin_range" | "set_online_status" | "get_friends_with_category" | "set_qq_avatar" | "get_file" | "forward_friend_single_msg" | "forward_group_single_msg" | "translate_en2zh" | "set_msg_emoji_like" | "send_forward_msg" | "mark_private_msg_as_read" | "mark_group_msg_as_read" | "get_friend_msg_history" | "create_collection" | "get_collection_list" | "set_self_longnick" | "get_recent_contact" | "_mark_all_as_read" | "get_profile_like" | "fetch_custom_face" | "fetch_emoji_like" | "get_emoji_likes" | "set_input_status" | "get_group_info_ex" | "get_group_detail_info" | "get_group_ignore_add_request" | "_del_group_notice" | "friend_poke" | "group_poke" | "nc_get_packet_status" | "nc_get_user_status" | "nc_get_rkey" | "get_group_shut_list" | "move_group_file" | "trans_group_file" | "rename_group_file" | "get_guild_list" | "get_guild_service_profile" | "get_group_ignored_notifies" | "set_group_sign" | "send_group_sign" | "send_packet" | "get_mini_app_ark" | "get_ai_record" | "get_ai_characters" | "send_group_ai_record" | "get_clientkey" | "send_poke" | "create_flash_task" | "send_flash_msg" | "get_share_link" | "download_fileset" | "get_fileset_info" | "get_flash_file_list" | "get_flash_file_url" | "get_fileset_id" | "send_online_file" | "send_online_folder" | "get_online_file_msg" | "receive_online_file" | "refuse_online_file" | "cancel_online_file" | "clean_stream_temp_file_async" | "test_download_stream_async" | "upload_file_stream_async" | "download_file_stream_async" | "download_file_record_stream_async" | "download_file_image_stream_async" | "del_group_album_media_async" | "set_group_album_media_like_async" | "do_group_album_comment_async" | "get_group_album_media_list_async" | "upload_image_to_qun_album_async" | "get_qun_album_list_async" | "set_group_todo_async" | "set_group_kick_members_async" | "set_group_robot_add_option_async" | "set_group_add_option_async" | "set_group_search_async" | "get_doubt_friends_add_request_async" | "set_doubt_friends_add_request_async" | "get_rkey_async" | "get_rkey_server_async" | "set_group_remark_async" | "get_private_file_url_async" | "click_inline_keyboard_button_async" | "get_unidirectional_friend_list_async" | "send_private_msg_async" | "send_group_msg_async" | "send_msg_async" | "delete_msg_async" | "get_msg_async" | "get_forward_msg_async" | "send_like_async" | "set_group_kick_async" | "set_group_ban_async" | "set_group_whole_ban_async" | "set_group_admin_async" | "set_group_card_async" | "set_group_name_async" | "set_group_leave_async" | "set_group_special_title_async" | "set_friend_add_request_async" | "set_friend_remark_async" | "set_group_add_request_async" | "get_login_info_async" | "get_stranger_info_async" | "get_friend_list_async" | "get_group_info_async" | "get_group_list_async" | "get_group_member_info_async" | "get_group_member_list_async" | "get_group_honor_info_async" | "get_cookies_async" | "get_csrf_token_async" | "get_credentials_async" | "get_record_async" | "get_image_async" | "can_send_image_async" | "can_send_record_async" | "get_status_async" | "get_version_info_async" | "set_restart_async" | "clean_cache_async" | "bot_exit_async" | "set_qq_profile_async" | "_get_model_show_async" | "_set_model_show_async" | "get_online_clients_async" | "delete_friend_async" | "mark_msg_as_read_async" | "send_group_forward_msg_async" | "send_private_forward_msg_async" | "get_group_msg_history_async" | "ocr_image_async" | ".ocr_image_async" | "get_group_system_msg_async" | "get_essence_msg_list_async" | "get_group_at_all_remain_async" | "set_group_portrait_async" | "set_essence_msg_async" | "delete_essence_msg_async" | "_send_group_notice_async" | "_get_group_notice_async" | "upload_group_file_async" | "delete_group_file_async" | "create_group_file_folder_async" | "delete_group_folder_async" | "get_group_file_system_info_async" | "get_group_root_files_async" | "get_group_files_by_folder_async" | "get_group_file_url_async" | "upload_private_file_async" | "download_file_async" | "check_url_safely_async" | ".handle_quick_operation_async" | "set_diy_online_status_async" | "ArkSharePeer_async" | "ArkShareGroup_async" | "send_group_ark_share_async" | "send_ark_share_async" | "get_robot_uin_range_async" | "set_online_status_async" | "get_friends_with_category_async" | "set_qq_avatar_async" | "get_file_async" | "forward_friend_single_msg_async" | "forward_group_single_msg_async" | "translate_en2zh_async" | "set_msg_emoji_like_async" | "send_forward_msg_async" | "mark_private_msg_as_read_async" | "mark_group_msg_as_read_async" | "get_friend_msg_history_async" | "create_collection_async" | "get_collection_list_async" | "set_self_longnick_async" | "get_recent_contact_async" | "_mark_all_as_read_async" | "get_profile_like_async" | "fetch_custom_face_async" | "fetch_emoji_like_async" | "get_emoji_likes_async" | "set_input_status_async" | "get_group_info_ex_async" | "get_group_detail_info_async" | "get_group_ignore_add_request_async" | "_del_group_notice_async" | "friend_poke_async" | "group_poke_async" | "nc_get_packet_status_async" | "nc_get_user_status_async" | "nc_get_rkey_async" | "get_group_shut_list_async" | "move_group_file_async" | "trans_group_file_async" | "rename_group_file_async" | "get_guild_list_async" | "get_guild_service_profile_async" | "get_group_ignored_notifies_async" | "set_group_sign_async" | "send_group_sign_async" | "send_packet_async" | "get_mini_app_ark_async" | "get_ai_record_async" | "get_ai_characters_async" | "send_group_ai_record_async" | "get_clientkey_async" | "send_poke_async" | "create_flash_task_async" | "send_flash_msg_async" | "get_share_link_async" | "download_fileset_async" | "get_fileset_info_async" | "get_flash_file_list_async" | "get_flash_file_url_async" | "get_fileset_id_async" | "send_online_file_async" | "send_online_folder_async" | "get_online_file_msg_async" | "receive_online_file_async" | "refuse_online_file_async" | "cancel_online_file_async" | "clean_stream_temp_file_rate_limited" | "test_download_stream_rate_limited" | "upload_file_stream_rate_limited" | "download_file_stream_rate_limited" | "download_file_record_stream_rate_limited" | "download_file_image_stream_rate_limited" | "del_group_album_media_rate_limited" | "set_group_album_media_like_rate_limited" | "do_group_album_comment_rate_limited" | "get_group_album_media_list_rate_limited" | "upload_image_to_qun_album_rate_limited" | "get_qun_album_list_rate_limited" | "set_group_todo_rate_limited" | "set_group_kick_members_rate_limited" | "set_group_robot_add_option_rate_limited" | "set_group_add_option_rate_limited" | "set_group_search_rate_limited" | "get_doubt_friends_add_request_rate_limited" | "set_doubt_friends_add_request_rate_limited" | "get_rkey_rate_limited" | "get_rkey_server_rate_limited" | "set_group_remark_rate_limited" | "get_private_file_url_rate_limited" | "click_inline_keyboard_button_rate_limited" | "get_unidirectional_friend_list_rate_limited" | "send_private_msg_rate_limited" | "send_group_msg_rate_limited" | "send_msg_rate_limited" | "delete_msg_rate_limited" | "get_msg_rate_limited" | "get_forward_msg_rate_limited" | "send_like_rate_limited" | "set_group_kick_rate_limited" | "set_group_ban_rate_limited" | "set_group_whole_ban_rate_limited" | "set_group_admin_rate_limited" | "set_group_card_rate_limited" | "set_group_name_rate_limited" | "set_group_leave_rate_limited" | "set_group_special_title_rate_limited" | "set_friend_add_request_rate_limited" | "set_friend_remark_rate_limited" | "set_group_add_request_rate_limited" | "get_login_info_rate_limited" | "get_stranger_info_rate_limited" | "get_friend_list_rate_limited" | "get_group_info_rate_limited" | "get_group_list_rate_limited" | "get_group_member_info_rate_limited" | "get_group_member_list_rate_limited" | "get_group_honor_info_rate_limited" | "get_cookies_rate_limited" | "get_csrf_token_rate_limited" | "get_credentials_rate_limited" | "get_record_rate_limited" | "get_image_rate_limited" | "can_send_image_rate_limited" | "can_send_record_rate_limited" | "get_status_rate_limited" | "get_version_info_rate_limited" | "set_restart_rate_limited" | "clean_cache_rate_limited" | "bot_exit_rate_limited" | "set_qq_profile_rate_limited" | "_get_model_show_rate_limited" | "_set_model_show_rate_limited" | "get_online_clients_rate_limited" | "delete_friend_rate_limited" | "mark_msg_as_read_rate_limited" | "send_group_forward_msg_rate_limited" | "send_private_forward_msg_rate_limited" | "get_group_msg_history_rate_limited" | "ocr_image_rate_limited" | ".ocr_image_rate_limited" | "get_group_system_msg_rate_limited" | "get_essence_msg_list_rate_limited" | "get_group_at_all_remain_rate_limited" | "set_group_portrait_rate_limited" | "set_essence_msg_rate_limited" | "delete_essence_msg_rate_limited" | "_send_group_notice_rate_limited" | "_get_group_notice_rate_limited" | "upload_group_file_rate_limited" | "delete_group_file_rate_limited" | "create_group_file_folder_rate_limited" | "delete_group_folder_rate_limited" | "get_group_file_system_info_rate_limited" | "get_group_root_files_rate_limited" | "get_group_files_by_folder_rate_limited" | "get_group_file_url_rate_limited" | "upload_private_file_rate_limited" | "download_file_rate_limited" | "check_url_safely_rate_limited" | ".handle_quick_operation_rate_limited" | "set_diy_online_status_rate_limited" | "ArkSharePeer_rate_limited" | "ArkShareGroup_rate_limited" | "send_group_ark_share_rate_limited" | "send_ark_share_rate_limited" | "get_robot_uin_range_rate_limited" | "set_online_status_rate_limited" | "get_friends_with_category_rate_limited" | "set_qq_avatar_rate_limited" | "get_file_rate_limited" | "forward_friend_single_msg_rate_limited" | "forward_group_single_msg_rate_limited" | "translate_en2zh_rate_limited" | "set_msg_emoji_like_rate_limited" | "send_forward_msg_rate_limited" | "mark_private_msg_as_read_rate_limited" | "mark_group_msg_as_read_rate_limited" | "get_friend_msg_history_rate_limited" | "create_collection_rate_limited" | "get_collection_list_rate_limited" | "set_self_longnick_rate_limited" | "get_recent_contact_rate_limited" | "_mark_all_as_read_rate_limited" | "get_profile_like_rate_limited" | "fetch_custom_face_rate_limited" | "fetch_emoji_like_rate_limited" | "get_emoji_likes_rate_limited" | "set_input_status_rate_limited" | "get_group_info_ex_rate_limited" | "get_group_detail_info_rate_limited" | "get_group_ignore_add_request_rate_limited" | "_del_group_notice_rate_limited" | "friend_poke_rate_limited" | "group_poke_rate_limited" | "nc_get_packet_status_rate_limited" | "nc_get_user_status_rate_limited" | "nc_get_rkey_rate_limited" | "get_group_shut_list_rate_limited" | "move_group_file_rate_limited" | "trans_group_file_rate_limited" | "rename_group_file_rate_limited" | "get_guild_list_rate_limited" | "get_guild_service_profile_rate_limited" | "get_group_ignored_notifies_rate_limited" | "set_group_sign_rate_limited" | "send_group_sign_rate_limited" | "send_packet_rate_limited" | "get_mini_app_ark_rate_limited" | "get_ai_record_rate_limited" | "get_ai_characters_rate_limited" | "send_group_ai_record_rate_limited" | "get_clientkey_rate_limited" | "send_poke_rate_limited" | "create_flash_task_rate_limited" | "send_flash_msg_rate_limited" | "get_share_link_rate_limited" | "download_fileset_rate_limited" | "get_fileset_info_rate_limited" | "get_flash_file_list_rate_limited" | "get_flash_file_url_rate_limited" | "get_fileset_id_rate_limited" | "send_online_file_rate_limited" | "send_online_folder_rate_limited" | "get_online_file_msg_rate_limited" | "receive_online_file_rate_limited" | "refuse_online_file_rate_limited" | "cancel_online_file_rate_limited">(actionName: K, params: unknown, adapter: string, config: NetworkAdapterConfig) => Promise<({
        get_msg: GetMsg;
        get_login_info: GetLoginInfo;
        get_friend_list: GetFriendList;
        get_group_list: GetGroupList;
        get_group_info: GetGroupInfo;
        get_group_member_info: GetGroupMemberInfo;
        send_msg: SendMsg;
        send_group_msg: SendGroupMsg;
        send_private_msg: SendPrivateMsg;
        delete_msg: DeleteMsg;
        get_version_info: GetVersionInfo;
        can_send_record: CanSendRecord;
        can_send_image: CanSendImage;
        get_status: GetStatus;
        send_forward_msg: GoCQHTTPSendForwardMsg;
        send_private_forward_msg: GoCQHTTPSendPrivateForwardMsg;
        send_group_forward_msg: GoCQHTTPSendGroupForwardMsg;
        get_stranger_info: GoCQHTTPGetStrangerInfo;
        send_like: SendLike;
        set_group_add_request: SetGroupAddRequest;
        set_group_leave: SetGroupLeave;
        set_friend_add_request: SetFriendAddRequest;
        set_group_whole_ban: SetGroupWholeBan;
        set_group_name: SetGroupName;
        set_group_ban: SetGroupBan;
        set_group_kick: SetGroupKick;
        set_group_admin: SetGroupAdmin;
        set_group_card: SetGroupCard;
        get_file: GetFile;
        get_image: GetImage;
        get_record: GetRecord;
        mark_private_msg_as_read: MarkPrivateMsgAsRead;
        mark_group_msg_as_read: MarkGroupMsgAsRead;
        mark_msg_as_read: GoCQHTTPMarkMsgAsRead;
        _mark_all_as_read: MarkAllMsgAsRead;
        upload_group_file: GoCQHTTPUploadGroupFile;
        set_qq_avatar: SetQQAvatar;
        download_file: GoCQHTTPDownloadFile;
        get_group_msg_history: GoCQHTTPGetGroupMsgHistory;
        get_forward_msg: GoCQHTTPGetForwardMsgAction;
        get_friend_msg_history: GetFriendMsgHistory;
        get_cookies: GetCookies;
        set_msg_emoji_like: SetMsgEmojiLike;
        get_robot_uin_range: GetRobotUinRange;
        set_online_status: SetOnlineStatus;
        _get_group_notice: GetGroupNotice;
        get_essence_msg_list: GetGroupEssence;
        forward_friend_single_msg: ForwardFriendSingleMsg;
        forward_group_single_msg: ForwardGroupSingleMsg;
        get_friends_with_category: GetFriendWithCategory;
        _send_group_notice: SendGroupNotice;
        get_group_honor_info: GetGroupHonorInfo;
        ".handle_quick_operation": GoCQHTTPHandleQuickAction;
        get_group_ignored_notifies: GetGroupIgnoredNotifies;
        get_online_clients: GetOnlineClient;
        ocr_image: OCRImage;
        ".ocr_image": IOCRImage;
        translate_en2zh: TranslateEnWordToZn;
        set_qq_profile: SetQQProfile;
        ArkSharePeer: SharePeer;
        ArkShareGroup: ShareGroupEx;
        send_group_ark_share: SendGroupArkShare;
        send_ark_share: SendArkShare;
        create_collection: CreateCollection;
        set_self_longnick: SetLongNick;
        delete_essence_msg: DelEssenceMsg;
        set_essence_msg: SetEssenceMsg;
        get_recent_contact: GetRecentContact;
        get_profile_like: GetProfileLike;
        set_group_portrait: SetGroupPortrait;
        fetch_custom_face: FetchCustomFace;
        upload_private_file: GoCQHTTPUploadPrivateFile;
        fetch_emoji_like: FetchEmojiLike;
        get_emoji_likes: GetEmojiLikes;
        set_input_status: SetInputStatus;
        get_csrf_token: GetCSRF;
        _del_group_notice: DelGroupNotice;
        get_group_info_ex: GetGroupInfoEx;
        delete_group_file: DeleteGroupFile;
        create_group_file_folder: CreateGroupFileFolder;
        delete_group_folder: DeleteGroupFileFolder;
        get_group_file_system_info: GetGroupFileSystemInfo;
        get_group_root_files: GetGroupRootFiles;
        get_group_files_by_folder: GetGroupFilesByFolder;
        get_group_system_msg: GetGroupSystemMsg;
        nc_get_packet_status: GetPacketStatus;
        nc_get_user_status: GetUserStatus;
        nc_get_rkey: GetRkey;
        set_group_special_title: SetSpecialTitle;
        get_group_shut_list: GetGroupShutList;
        get_group_member_list: GetGroupMemberList;
        get_group_file_url: GetGroupFileUrl;
        get_credentials: GetCredentials;
        set_restart: SetRestart;
        set_group_sign: SetGroupSign;
        send_group_sign: SendGroupSign;
        get_group_at_all_remain: GoCQHTTPGetGroupAtAllRemain;
        check_url_safely: GoCQHTTPCheckUrlSafely;
        _get_model_show: GoCQHTTPGetModelShow;
        _set_model_show: GoCQHTTPSetModelShow;
        delete_friend: GoCQHTTPDeleteFriend;
        get_mini_app_ark: GetMiniAppArk;
        get_ai_record: GetAiRecord;
        send_group_ai_record: SendGroupAiRecord;
        get_ai_characters: GetAiCharacters;
        get_guild_list: GetGuildList;
        get_guild_service_profile: GetGuildProfile;
        get_clientkey: GetClientkey;
        send_packet: SendPacket;
        send_poke: SendPoke;
        group_poke: GroupPoke;
        friend_poke: FriendPoke;
        set_diy_online_status: SetDiyOnlineStatus;
        bot_exit: BotExit;
        click_inline_keyboard_button: ClickInlineKeyboardButton;
        get_private_file_url: GetPrivateFileUrl;
        get_unidirectional_friend_list: GetUnidirectionalFriendList;
        set_group_remark: SetGroupRemark;
        move_group_file: MoveGroupFile;
        trans_group_file: TransGroupFile;
        rename_group_file: RenameGroupFile;
        get_rkey_server: GetRkeyServer;
        get_rkey: GetRkeyEx;
        clean_cache: CleanCache;
        set_friend_remark: SetFriendRemark;
        set_doubt_friends_add_request: SetDoubtFriendsAddRequest;
        get_doubt_friends_add_request: GetDoubtFriendsAddRequest;
        set_group_add_option: SetGroupAddOption;
        set_group_search: SetGroupSearch;
        set_group_robot_add_option: SetGroupRobotAddOption;
        set_group_kick_members: SetGroupKickMembers;
        get_group_detail_info: GetGroupDetailInfo;
        get_group_ignore_add_request: GetGroupAddRequest;
        get_collection_list: GetCollectionList;
        set_group_todo: SetGroupTodo;
        get_qun_album_list: GetQunAlbumList;
        upload_image_to_qun_album: UploadImageToQunAlbum;
        do_group_album_comment: DoGroupAlbumComment;
        get_group_album_media_list: GetGroupAlbumMediaList;
        set_group_album_media_like: SetGroupAlbumMediaLike;
        del_group_album_media: DelGroupAlbumMedia;
        clean_stream_temp_file: CleanStreamTempFile;
        download_file_stream: DownloadFileStream;
        download_file_record_stream: DownloadFileRecordStream;
        download_file_image_stream: DownloadFileImageStream;
        test_download_stream: TestDownloadStream;
        upload_file_stream: UploadFileStream;
        create_flash_task: CreateFlashTask;
        send_flash_msg: SendFlashMsg;
        get_flash_file_list: GetFlashFileList;
        get_flash_file_url: GetFlashFileUrl;
        get_share_link: GetShareLink;
        get_fileset_info: GetFilesetInfo;
        download_fileset: DownloadFileset;
        get_online_file_msg: GetOnlineFileMessages;
        send_online_file: SendOnlineFile;
        send_online_folder: SendOnlineFolder;
        cancel_online_file: CancelOnlineFile;
        receive_online_file: ReceiveOnlineFile;
        refuse_online_file: RefuseOnlineFile;
        get_fileset_id: GetFilesetId;
    } & {
        get_msg_async: GetMsg;
        get_login_info_async: GetLoginInfo;
        get_friend_list_async: GetFriendList;
        get_group_list_async: GetGroupList;
        get_group_info_async: GetGroupInfo;
        get_group_member_info_async: GetGroupMemberInfo;
        send_msg_async: SendMsg;
        send_group_msg_async: SendGroupMsg;
        send_private_msg_async: SendPrivateMsg;
        delete_msg_async: DeleteMsg;
        get_version_info_async: GetVersionInfo;
        can_send_record_async: CanSendRecord;
        can_send_image_async: CanSendImage;
        get_status_async: GetStatus;
        send_forward_msg_async: GoCQHTTPSendForwardMsg;
        send_private_forward_msg_async: GoCQHTTPSendPrivateForwardMsg;
        send_group_forward_msg_async: GoCQHTTPSendGroupForwardMsg;
        get_stranger_info_async: GoCQHTTPGetStrangerInfo;
        send_like_async: SendLike;
        set_group_add_request_async: SetGroupAddRequest;
        set_group_leave_async: SetGroupLeave;
        set_friend_add_request_async: SetFriendAddRequest;
        set_group_whole_ban_async: SetGroupWholeBan;
        set_group_name_async: SetGroupName;
        set_group_ban_async: SetGroupBan;
        set_group_kick_async: SetGroupKick;
        set_group_admin_async: SetGroupAdmin;
        set_group_card_async: SetGroupCard;
        get_file_async: GetFile;
        get_image_async: GetImage;
        get_record_async: GetRecord;
        mark_private_msg_as_read_async: MarkPrivateMsgAsRead;
        mark_group_msg_as_read_async: MarkGroupMsgAsRead;
        mark_msg_as_read_async: GoCQHTTPMarkMsgAsRead;
        _mark_all_as_read_async: MarkAllMsgAsRead;
        upload_group_file_async: GoCQHTTPUploadGroupFile;
        set_qq_avatar_async: SetQQAvatar;
        download_file_async: GoCQHTTPDownloadFile;
        get_group_msg_history_async: GoCQHTTPGetGroupMsgHistory;
        get_forward_msg_async: GoCQHTTPGetForwardMsgAction;
        get_friend_msg_history_async: GetFriendMsgHistory;
        get_cookies_async: GetCookies;
        set_msg_emoji_like_async: SetMsgEmojiLike;
        get_robot_uin_range_async: GetRobotUinRange;
        set_online_status_async: SetOnlineStatus;
        _get_group_notice_async: GetGroupNotice;
        get_essence_msg_list_async: GetGroupEssence;
        forward_friend_single_msg_async: ForwardFriendSingleMsg;
        forward_group_single_msg_async: ForwardGroupSingleMsg;
        get_friends_with_category_async: GetFriendWithCategory;
        _send_group_notice_async: SendGroupNotice;
        get_group_honor_info_async: GetGroupHonorInfo;
        ".handle_quick_operation_async": GoCQHTTPHandleQuickAction;
        get_group_ignored_notifies_async: GetGroupIgnoredNotifies;
        get_online_clients_async: GetOnlineClient;
        ocr_image_async: OCRImage;
        ".ocr_image_async": IOCRImage;
        translate_en2zh_async: TranslateEnWordToZn;
        set_qq_profile_async: SetQQProfile;
        ArkSharePeer_async: SharePeer;
        ArkShareGroup_async: ShareGroupEx;
        send_group_ark_share_async: SendGroupArkShare;
        send_ark_share_async: SendArkShare;
        create_collection_async: CreateCollection;
        set_self_longnick_async: SetLongNick;
        delete_essence_msg_async: DelEssenceMsg;
        set_essence_msg_async: SetEssenceMsg;
        get_recent_contact_async: GetRecentContact;
        get_profile_like_async: GetProfileLike;
        set_group_portrait_async: SetGroupPortrait;
        fetch_custom_face_async: FetchCustomFace;
        upload_private_file_async: GoCQHTTPUploadPrivateFile;
        fetch_emoji_like_async: FetchEmojiLike;
        get_emoji_likes_async: GetEmojiLikes;
        set_input_status_async: SetInputStatus;
        get_csrf_token_async: GetCSRF;
        _del_group_notice_async: DelGroupNotice;
        get_group_info_ex_async: GetGroupInfoEx;
        delete_group_file_async: DeleteGroupFile;
        create_group_file_folder_async: CreateGroupFileFolder;
        delete_group_folder_async: DeleteGroupFileFolder;
        get_group_file_system_info_async: GetGroupFileSystemInfo;
        get_group_root_files_async: GetGroupRootFiles;
        get_group_files_by_folder_async: GetGroupFilesByFolder;
        get_group_system_msg_async: GetGroupSystemMsg;
        nc_get_packet_status_async: GetPacketStatus;
        nc_get_user_status_async: GetUserStatus;
        nc_get_rkey_async: GetRkey;
        set_group_special_title_async: SetSpecialTitle;
        get_group_shut_list_async: GetGroupShutList;
        get_group_member_list_async: GetGroupMemberList;
        get_group_file_url_async: GetGroupFileUrl;
        get_credentials_async: GetCredentials;
        set_restart_async: SetRestart;
        set_group_sign_async: SetGroupSign;
        send_group_sign_async: SendGroupSign;
        get_group_at_all_remain_async: GoCQHTTPGetGroupAtAllRemain;
        check_url_safely_async: GoCQHTTPCheckUrlSafely;
        _get_model_show_async: GoCQHTTPGetModelShow;
        _set_model_show_async: GoCQHTTPSetModelShow;
        delete_friend_async: GoCQHTTPDeleteFriend;
        get_mini_app_ark_async: GetMiniAppArk;
        get_ai_record_async: GetAiRecord;
        send_group_ai_record_async: SendGroupAiRecord;
        get_ai_characters_async: GetAiCharacters;
        get_guild_list_async: GetGuildList;
        get_guild_service_profile_async: GetGuildProfile;
        get_clientkey_async: GetClientkey;
        send_packet_async: SendPacket;
        send_poke_async: SendPoke;
        group_poke_async: GroupPoke;
        friend_poke_async: FriendPoke;
        set_diy_online_status_async: SetDiyOnlineStatus;
        bot_exit_async: BotExit;
        click_inline_keyboard_button_async: ClickInlineKeyboardButton;
        get_private_file_url_async: GetPrivateFileUrl;
        get_unidirectional_friend_list_async: GetUnidirectionalFriendList;
        set_group_remark_async: SetGroupRemark;
        move_group_file_async: MoveGroupFile;
        trans_group_file_async: TransGroupFile;
        rename_group_file_async: RenameGroupFile;
        get_rkey_server_async: GetRkeyServer;
        get_rkey_async: GetRkeyEx;
        clean_cache_async: CleanCache;
        set_friend_remark_async: SetFriendRemark;
        set_doubt_friends_add_request_async: SetDoubtFriendsAddRequest;
        get_doubt_friends_add_request_async: GetDoubtFriendsAddRequest;
        set_group_add_option_async: SetGroupAddOption;
        set_group_search_async: SetGroupSearch;
        set_group_robot_add_option_async: SetGroupRobotAddOption;
        set_group_kick_members_async: SetGroupKickMembers;
        get_group_detail_info_async: GetGroupDetailInfo;
        get_group_ignore_add_request_async: GetGroupAddRequest;
        get_collection_list_async: GetCollectionList;
        set_group_todo_async: SetGroupTodo;
        get_qun_album_list_async: GetQunAlbumList;
        upload_image_to_qun_album_async: UploadImageToQunAlbum;
        do_group_album_comment_async: DoGroupAlbumComment;
        get_group_album_media_list_async: GetGroupAlbumMediaList;
        set_group_album_media_like_async: SetGroupAlbumMediaLike;
        del_group_album_media_async: DelGroupAlbumMedia;
        clean_stream_temp_file_async: CleanStreamTempFile;
        download_file_stream_async: DownloadFileStream;
        download_file_record_stream_async: DownloadFileRecordStream;
        download_file_image_stream_async: DownloadFileImageStream;
        test_download_stream_async: TestDownloadStream;
        upload_file_stream_async: UploadFileStream;
        create_flash_task_async: CreateFlashTask;
        send_flash_msg_async: SendFlashMsg;
        get_flash_file_list_async: GetFlashFileList;
        get_flash_file_url_async: GetFlashFileUrl;
        get_share_link_async: GetShareLink;
        get_fileset_info_async: GetFilesetInfo;
        download_fileset_async: DownloadFileset;
        get_online_file_msg_async: GetOnlineFileMessages;
        send_online_file_async: SendOnlineFile;
        send_online_folder_async: SendOnlineFolder;
        cancel_online_file_async: CancelOnlineFile;
        receive_online_file_async: ReceiveOnlineFile;
        refuse_online_file_async: RefuseOnlineFile;
        get_fileset_id_async: GetFilesetId;
    } & {
        get_msg_rate_limited: GetMsg;
        get_login_info_rate_limited: GetLoginInfo;
        get_friend_list_rate_limited: GetFriendList;
        get_group_list_rate_limited: GetGroupList;
        get_group_info_rate_limited: GetGroupInfo;
        get_group_member_info_rate_limited: GetGroupMemberInfo;
        send_msg_rate_limited: SendMsg;
        send_group_msg_rate_limited: SendGroupMsg;
        send_private_msg_rate_limited: SendPrivateMsg;
        delete_msg_rate_limited: DeleteMsg;
        get_version_info_rate_limited: GetVersionInfo;
        can_send_record_rate_limited: CanSendRecord;
        can_send_image_rate_limited: CanSendImage;
        get_status_rate_limited: GetStatus;
        send_forward_msg_rate_limited: GoCQHTTPSendForwardMsg;
        send_private_forward_msg_rate_limited: GoCQHTTPSendPrivateForwardMsg;
        send_group_forward_msg_rate_limited: GoCQHTTPSendGroupForwardMsg;
        get_stranger_info_rate_limited: GoCQHTTPGetStrangerInfo;
        send_like_rate_limited: SendLike;
        set_group_add_request_rate_limited: SetGroupAddRequest;
        set_group_leave_rate_limited: SetGroupLeave;
        set_friend_add_request_rate_limited: SetFriendAddRequest;
        set_group_whole_ban_rate_limited: SetGroupWholeBan;
        set_group_name_rate_limited: SetGroupName;
        set_group_ban_rate_limited: SetGroupBan;
        set_group_kick_rate_limited: SetGroupKick;
        set_group_admin_rate_limited: SetGroupAdmin;
        set_group_card_rate_limited: SetGroupCard;
        get_file_rate_limited: GetFile;
        get_image_rate_limited: GetImage;
        get_record_rate_limited: GetRecord;
        mark_private_msg_as_read_rate_limited: MarkPrivateMsgAsRead;
        mark_group_msg_as_read_rate_limited: MarkGroupMsgAsRead;
        mark_msg_as_read_rate_limited: GoCQHTTPMarkMsgAsRead;
        _mark_all_as_read_rate_limited: MarkAllMsgAsRead;
        upload_group_file_rate_limited: GoCQHTTPUploadGroupFile;
        set_qq_avatar_rate_limited: SetQQAvatar;
        download_file_rate_limited: GoCQHTTPDownloadFile;
        get_group_msg_history_rate_limited: GoCQHTTPGetGroupMsgHistory;
        get_forward_msg_rate_limited: GoCQHTTPGetForwardMsgAction;
        get_friend_msg_history_rate_limited: GetFriendMsgHistory;
        get_cookies_rate_limited: GetCookies;
        set_msg_emoji_like_rate_limited: SetMsgEmojiLike;
        get_robot_uin_range_rate_limited: GetRobotUinRange;
        set_online_status_rate_limited: SetOnlineStatus;
        _get_group_notice_rate_limited: GetGroupNotice;
        get_essence_msg_list_rate_limited: GetGroupEssence;
        forward_friend_single_msg_rate_limited: ForwardFriendSingleMsg;
        forward_group_single_msg_rate_limited: ForwardGroupSingleMsg;
        get_friends_with_category_rate_limited: GetFriendWithCategory;
        _send_group_notice_rate_limited: SendGroupNotice;
        get_group_honor_info_rate_limited: GetGroupHonorInfo;
        ".handle_quick_operation_rate_limited": GoCQHTTPHandleQuickAction;
        get_group_ignored_notifies_rate_limited: GetGroupIgnoredNotifies;
        get_online_clients_rate_limited: GetOnlineClient;
        ocr_image_rate_limited: OCRImage;
        ".ocr_image_rate_limited": IOCRImage;
        translate_en2zh_rate_limited: TranslateEnWordToZn;
        set_qq_profile_rate_limited: SetQQProfile;
        ArkSharePeer_rate_limited: SharePeer;
        ArkShareGroup_rate_limited: ShareGroupEx;
        send_group_ark_share_rate_limited: SendGroupArkShare;
        send_ark_share_rate_limited: SendArkShare;
        create_collection_rate_limited: CreateCollection;
        set_self_longnick_rate_limited: SetLongNick;
        delete_essence_msg_rate_limited: DelEssenceMsg;
        set_essence_msg_rate_limited: SetEssenceMsg;
        get_recent_contact_rate_limited: GetRecentContact;
        get_profile_like_rate_limited: GetProfileLike;
        set_group_portrait_rate_limited: SetGroupPortrait;
        fetch_custom_face_rate_limited: FetchCustomFace;
        upload_private_file_rate_limited: GoCQHTTPUploadPrivateFile;
        fetch_emoji_like_rate_limited: FetchEmojiLike;
        get_emoji_likes_rate_limited: GetEmojiLikes;
        set_input_status_rate_limited: SetInputStatus;
        get_csrf_token_rate_limited: GetCSRF;
        _del_group_notice_rate_limited: DelGroupNotice;
        get_group_info_ex_rate_limited: GetGroupInfoEx;
        delete_group_file_rate_limited: DeleteGroupFile;
        create_group_file_folder_rate_limited: CreateGroupFileFolder;
        delete_group_folder_rate_limited: DeleteGroupFileFolder;
        get_group_file_system_info_rate_limited: GetGroupFileSystemInfo;
        get_group_root_files_rate_limited: GetGroupRootFiles;
        get_group_files_by_folder_rate_limited: GetGroupFilesByFolder;
        get_group_system_msg_rate_limited: GetGroupSystemMsg;
        nc_get_packet_status_rate_limited: GetPacketStatus;
        nc_get_user_status_rate_limited: GetUserStatus;
        nc_get_rkey_rate_limited: GetRkey;
        set_group_special_title_rate_limited: SetSpecialTitle;
        get_group_shut_list_rate_limited: GetGroupShutList;
        get_group_member_list_rate_limited: GetGroupMemberList;
        get_group_file_url_rate_limited: GetGroupFileUrl;
        get_credentials_rate_limited: GetCredentials;
        set_restart_rate_limited: SetRestart;
        set_group_sign_rate_limited: SetGroupSign;
        send_group_sign_rate_limited: SendGroupSign;
        get_group_at_all_remain_rate_limited: GoCQHTTPGetGroupAtAllRemain;
        check_url_safely_rate_limited: GoCQHTTPCheckUrlSafely;
        _get_model_show_rate_limited: GoCQHTTPGetModelShow;
        _set_model_show_rate_limited: GoCQHTTPSetModelShow;
        delete_friend_rate_limited: GoCQHTTPDeleteFriend;
        get_mini_app_ark_rate_limited: GetMiniAppArk;
        get_ai_record_rate_limited: GetAiRecord;
        send_group_ai_record_rate_limited: SendGroupAiRecord;
        get_ai_characters_rate_limited: GetAiCharacters;
        get_guild_list_rate_limited: GetGuildList;
        get_guild_service_profile_rate_limited: GetGuildProfile;
        get_clientkey_rate_limited: GetClientkey;
        send_packet_rate_limited: SendPacket;
        send_poke_rate_limited: SendPoke;
        group_poke_rate_limited: GroupPoke;
        friend_poke_rate_limited: FriendPoke;
        set_diy_online_status_rate_limited: SetDiyOnlineStatus;
        bot_exit_rate_limited: BotExit;
        click_inline_keyboard_button_rate_limited: ClickInlineKeyboardButton;
        get_private_file_url_rate_limited: GetPrivateFileUrl;
        get_unidirectional_friend_list_rate_limited: GetUnidirectionalFriendList;
        set_group_remark_rate_limited: SetGroupRemark;
        move_group_file_rate_limited: MoveGroupFile;
        trans_group_file_rate_limited: TransGroupFile;
        rename_group_file_rate_limited: RenameGroupFile;
        get_rkey_server_rate_limited: GetRkeyServer;
        get_rkey_rate_limited: GetRkeyEx;
        clean_cache_rate_limited: CleanCache;
        set_friend_remark_rate_limited: SetFriendRemark;
        set_doubt_friends_add_request_rate_limited: SetDoubtFriendsAddRequest;
        get_doubt_friends_add_request_rate_limited: GetDoubtFriendsAddRequest;
        set_group_add_option_rate_limited: SetGroupAddOption;
        set_group_search_rate_limited: SetGroupSearch;
        set_group_robot_add_option_rate_limited: SetGroupRobotAddOption;
        set_group_kick_members_rate_limited: SetGroupKickMembers;
        get_group_detail_info_rate_limited: GetGroupDetailInfo;
        get_group_ignore_add_request_rate_limited: GetGroupAddRequest;
        get_collection_list_rate_limited: GetCollectionList;
        set_group_todo_rate_limited: SetGroupTodo;
        get_qun_album_list_rate_limited: GetQunAlbumList;
        upload_image_to_qun_album_rate_limited: UploadImageToQunAlbum;
        do_group_album_comment_rate_limited: DoGroupAlbumComment;
        get_group_album_media_list_rate_limited: GetGroupAlbumMediaList;
        set_group_album_media_like_rate_limited: SetGroupAlbumMediaLike;
        del_group_album_media_rate_limited: DelGroupAlbumMedia;
        clean_stream_temp_file_rate_limited: CleanStreamTempFile;
        download_file_stream_rate_limited: DownloadFileStream;
        download_file_record_stream_rate_limited: DownloadFileRecordStream;
        download_file_image_stream_rate_limited: DownloadFileImageStream;
        test_download_stream_rate_limited: TestDownloadStream;
        upload_file_stream_rate_limited: UploadFileStream;
        create_flash_task_rate_limited: CreateFlashTask;
        send_flash_msg_rate_limited: SendFlashMsg;
        get_flash_file_list_rate_limited: GetFlashFileList;
        get_flash_file_url_rate_limited: GetFlashFileUrl;
        get_share_link_rate_limited: GetShareLink;
        get_fileset_info_rate_limited: GetFilesetInfo;
        download_fileset_rate_limited: DownloadFileset;
        get_online_file_msg_rate_limited: GetOnlineFileMessages;
        send_online_file_rate_limited: SendOnlineFile;
        send_online_folder_rate_limited: SendOnlineFolder;
        cancel_online_file_rate_limited: CancelOnlineFile;
        receive_online_file_rate_limited: ReceiveOnlineFile;
        refuse_online_file_rate_limited: RefuseOnlineFile;
        get_fileset_id_rate_limited: GetFilesetId;
    })[K] extends OneBotAction<any, infer R> ? R : never>;
};
export type ActionMap = ReturnType<typeof createActionMap>;
